<?php

namespace Tests\Feature;

use Illuminate\Support\Facades\Redis;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class TrendingThreadTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Redis::del('trending_threads');
    }


    use RefreshDatabase;
    /** @test */
    public function it_increments_a_thread_score_each_time_it_is_read()
    {
        $this->withoutExceptionHandling();

        $this->assertEmpty(Redis::zrevrange('trending_threads', 0, -1));

        $thread = create('App\Thread');

        $this->call('GET', $thread->path());

        $thrending = Redis::zrevrange('trending_threads', 0, -1);

        $this->assertCount(1, $thrending);

        $this->assertEquals($thread->title, json_decode($thrending[0])->title);
    }
}
