<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{
    use Favoritable, RecordsActivity;


    protected $guarded = [];

    protected $appends = ['favoritesCount', 'isFavorited', 'isBest'];

    protected $with = ['owner', 'favorites'];

    public function owner()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($reply) {
            $reply->thread->increment('replies_count');
        });

        static::deleted(function ($reply) {
//            if ($reply->isBest()) {
//                $reply->thread->update(['best_reply_id' => null]);
//            }

            $reply->thread->decrement('replies_count');
        });
    }

    public function thread()
    {
        return $this->belongsTo('App\Thread');
    }
    
    public function wasJustPublished()
    {
        return $this->created_at->gt(Carbon::now()->subMinute());
    }

    public function path()
    {
        return $this->thread->path() . '#reply-' . $this->id;
    }
    
    public function mentionedUsers()
    {
        preg_match_all('/@([\w\-]+)/', $this->body, $matches);

        return $matches[1];

    }
    
    public function setBodyAttribute($body)
    {
        $this->attributes['body'] = preg_replace('/@([\w\-]+)/', '<a href="/profiles/$1">$0</a>', $body);
    }

    public function isBest()
    {
        return $this->thread->best_reply_id == $this->id;
    }
    
    public function getIsBestAttribute()
    {
        return $this->isBest();
    }
}
